Indicate which preferences modal layouts support the serviceCounterLabel
orestbida/cookieconsent pull request #535
Opened 2023-06-22 08:30 UTC by MoritzLost

Improves documentation related to #533.

2023-06-22 22:59 UTC, orestbida requested changes
I think it's better to state that the label is hidden when the `bar` layout is selected or when the viewport is narrow.

2023-06-23 09:16 UTC, MoritzLost commented
@orestbida Fair enough, I've changed the wording!

2023-06-24 01:50 UTC, orestbida approved these changes

2023-06-24 01:51 UTC, merged

2023-06-24 01:51 UTC, orestbida commented
Thanks for your contribution!